version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: iprogrammer
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: notes123
      DB_NAME: iprogrammer
    volumes:
      - ./icoder_docker:/var/www/html
volumes:
  dbdata: